-- MySQL Script generated by MySQL Workbench
-- Sex 27 Mai 2016 15:48:44 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trabalho
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trabalho` ;

-- -----------------------------------------------------
-- Schema trabalho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho` DEFAULT CHARACTER SET latin1 ;
USE `trabalho` ;

-- -----------------------------------------------------
-- Table `trabalho`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho`.`clientes` ;

CREATE TABLE IF NOT EXISTS `trabalho`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `idade` INT NULL COMMENT '',
  `sexo` CHAR(1) NULL COMMENT '',
  `usuario` VARCHAR(60) NOT NULL COMMENT '',
  `senha` VARCHAR(60) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`companhias_aereas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho`.`companhias_aereas` ;

CREATE TABLE IF NOT EXISTS `trabalho`.`companhias_aereas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`avioes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho`.`avioes` ;

CREATE TABLE IF NOT EXISTS `trabalho`.`avioes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(60) NOT NULL COMMENT '',
  `descricao` VARCHAR(150) NULL COMMENT '',
  `companhias_areas_id` INT NOT NULL COMMENT '',
  `numero_assentos` INT NOT NULL COMMENT '',
  `valor_aviao` DECIMAL(12,2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_avioes_companhiasAereas1_idx` (`companhias_areas_id` ASC)  COMMENT '',
  CONSTRAINT `fk_avioes_companhiasAereas1`
    FOREIGN KEY (`companhias_areas_id`)
    REFERENCES `trabalho`.`companhias_aereas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`aeroportos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho`.`aeroportos` ;

CREATE TABLE IF NOT EXISTS `trabalho`.`aeroportos` (
  `id` INT NOT NULL COMMENT '',
  `nome` VARCHAR(60) NOT NULL COMMENT '',
  `sigla` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`voos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho`.`voos` ;

CREATE TABLE IF NOT EXISTS `trabalho`.`voos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `horario_partida` DATETIME NULL COMMENT '',
  `horario_chegada` DATETIME NULL COMMENT '',
  `avioes_id` INT NOT NULL COMMENT '',
  `partida` INT NOT NULL COMMENT '',
  `chegada` INT NOT NULL COMMENT '',
  `data_voo` DATE NULL COMMENT '',
  `valor_voo` DECIMAL(12,2) NULL COMMENT '',
  `promocao` TINYINT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_voo_avioes1_idx` (`avioes_id` ASC)  COMMENT '',
  INDEX `fk_voo_aeroportos1_idx` (`partida` ASC)  COMMENT '',
  INDEX `fk_voos_aeroportos1_idx` (`chegada` ASC)  COMMENT '',
  CONSTRAINT `fk_voo_avioes1`
    FOREIGN KEY (`avioes_id`)
    REFERENCES `trabalho`.`avioes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voo_aeroportos1`
    FOREIGN KEY (`partida`)
    REFERENCES `trabalho`.`aeroportos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voos_aeroportos1`
    FOREIGN KEY (`chegada`)
    REFERENCES `trabalho`.`aeroportos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho`.`categorias` ;

CREATE TABLE IF NOT EXISTS `trabalho`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(100) NOT NULL COMMENT '',
  `taxa` DECIMAL(2,2) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`passagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho`.`passagens` ;

CREATE TABLE IF NOT EXISTS `trabalho`.`passagens` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `voo_id` INT NOT NULL COMMENT '',
  `validade` DATE NULL COMMENT '',
  `categorias_id` INT NOT NULL COMMENT '',
  `valor_` DECIMAL(12,2) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_passagens_voo1_idx` (`voo_id` ASC)  COMMENT '',
  INDEX `fk_passagens_categorias1_idx` (`categorias_id` ASC)  COMMENT '',
  CONSTRAINT `fk_passagens_voo1`
    FOREIGN KEY (`voo_id`)
    REFERENCES `trabalho`.`voos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passagens_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `trabalho`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`categorias_avioes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho`.`categorias_avioes` ;

CREATE TABLE IF NOT EXISTS `trabalho`.`categorias_avioes` (
  `categorias_id` INT NOT NULL COMMENT '',
  `avioes_id` INT NOT NULL COMMENT '',
  `numeros_poltronas` INT NOT NULL COMMENT '',
  PRIMARY KEY (`categorias_id`, `avioes_id`)  COMMENT '',
  INDEX `fk_categoriasAcentos_has_avioes_avioes1_idx` (`avioes_id` ASC)  COMMENT '',
  INDEX `fk_categoriasAcentos_has_avioes_categoriasAcentos1_idx` (`categorias_id` ASC)  COMMENT '',
  CONSTRAINT `fk_categoriasAcentos_has_avioes_categoriasAcentos1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `trabalho`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoriasAcentos_has_avioes_avioes1`
    FOREIGN KEY (`avioes_id`)
    REFERENCES `trabalho`.`avioes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho`.`cliente_passagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabalho`.`cliente_passagens` ;

CREATE TABLE IF NOT EXISTS `trabalho`.`cliente_passagens` (
  `cliente_id` INT NOT NULL COMMENT '',
  `passagens_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`cliente_id`, `passagens_id`)  COMMENT '',
  INDEX `fk_cliente_has_passagens_passagens1_idx` (`passagens_id` ASC)  COMMENT '',
  INDEX `fk_cliente_has_passagens_cliente1_idx` (`cliente_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cliente_has_passagens_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `trabalho`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_passagens_passagens1`
    FOREIGN KEY (`passagens_id`)
    REFERENCES `trabalho`.`passagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
