/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.libraries;


import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Matheus
 */
public class ComboWeb extends javax.swing.JPanel {

    JComboBox combo;
    
    ArrayList<String> aeroportos = null;
    CustomJComboBox custom = new CustomJComboBox(aeroportos);
    
    /**
     * Creates new form ComboWeb
     */
    public ComboWeb() {
        initComponents();
        combo = custom;
        combo.setBounds(5, 5, 250, 25);
        combo.setEditable(true);
        this.add(combo);
    }

    public void setAeroportos(ArrayList<String[]> aeroportos) {
        
        ArrayList<String> array = new ArrayList();
        
        for (int i = 0; i < aeroportos.size(); i++) {
            array.add(aeroportos.get(i)[0]);
        }
        
        custom.refreshList(array);
        
        this.aeroportos = array;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
